### PR TITLE
fix: various bug fixes for Electron release

### LINKED ISSUE #33: App icon is too large on macOS
image

### LINKED ISSUE #34: Clicking "Copy" resets all colors
When the app runs in Electron, clicking any of the Copy buttons in the UI resets all colors

### PR DESCRIPTION
**Pull request by fmaclen**
Closes #34 
Closes #33

### CODE REVIEW

File: src/lib/components/ButtonCopy.svelte [hunk 1]
```diff
@@ -1,9 +1,12 @@
...
-	}
 </script>
 
-<button title="Copy" class="button-copy" onclick={copyContent}>Copy</button>
+<button
+	type="button"
+	title="Copy"
+	class="button-copy"
+	onclick={() => navigator.clipboard.writeText(content)}
+>
```
Comment (fmaclen) [inline src/lib/components/ButtonCopy.svelte:10]: @GregoMac1 These buttons were missing `type="button"` which when viewing the static site were behaving as `type="submit"` which was reloading the page.
